image: atlassian/default-image:2
pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update -y 
            - apt-get -y install python-dev
            - apt-get -y install python-pip
            - pip install awscli
            - apt-get install -y zip 
            - zip -r deploy.zip .
            - aws s3 cp deploy.zip s3://translation.tool.mt